In [13]:
import torch
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
torch.cuda.is_available()


False

# Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big error with pytorch and deeplearning
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device

In [14]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,# what datatype is the tensor (e.g float32 float16)
                               device="cpu",#  Defing what it should the processor be "cpu" or "gpu"
                               requires_grad=False # Whether or not to track gradients with this tensors operation
                               ) 
float_32_tensor

tensor([3., 6., 9.])

In [15]:
float_32_tensor.dtype

torch.float32

In [16]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [17]:
combined_tensor = float_16_tensor*float_32_tensor
combined_tensor.dtype

torch.float32

### Gettting information from tensors (tenosr attribute)
1. Tensor not right datatype - to do get datatype from a  tensor,can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensor not on the right device - to get device from a tensor,can use `tensor.device`

In [31]:
# Create a tensor
some_tensor32 = torch.rand((3,4))
some_tensor16 = some_tensor32.type(torch.float16)*1000//1

In [32]:
# Find out details about some tensor
print(some_tensor16)
print(f"Datatype of tensor: {some_tensor16.dtype}")
print(f"Shape of Tensor: {some_tensor16.shape}")
print(f"Device tensro is on:{some_tensor16.device}")              

tensor([[398., 304., 325., 773.],
        [157., 134., 305., 333.],
        [195., 929., 610., 130.]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of Tensor: torch.Size([3, 4])
Device tensro is on:cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


### Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning
1. Element-wise multiplication

2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The  **inner dimentions** must match:
* ` (3,2) @ (3,2)` won't work
* ` (2,3) @ (3,2) ` will work
* ` (3,2) @ (2,3) ` will work
2. The resulting matrix has the shape of the **outer dimention** 
* ` (2,3) @ (3,2) ` -> `(2,2)`
* ` (3,2) @ (2,3) ` -> `(2,3)`

In [53]:
%time
MATRIX_1 = torch.tensor(range(1,1000000))
torch.matmul(MATRIX_1,MATRIX_1)

CPU times: total: 0 ns
Wall time: 12.9 μs


tensor(333332833333500000)

In [54]:
%time
value = 0
for i in range(len(MATRIX_1)):
    value += MATRIX_1[i] * MATRIX_1[i]
value

CPU times: total: 0 ns
Wall time: 6.91 μs


tensor(333332833333500000)

### One of the most common errors in deep learning: shape errors

In [59]:
torch.matmul(torch.rand(3,2),torch.rand(2,2))

tensor([[1.3285, 0.4548],
        [0.8819, 0.3272],
        [0.7051, 0.3258]])

In [ ]:
# Shape for matrix multiplication
tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])
tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)