In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.1+cpu


## Introduction to Tensors

### Creating  tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([[7,7],[7,7]])
 

In [7]:
vector.ndim

2

In [8]:
vector.shape

torch.Size([2, 2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],[4,5,8],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 8],
         [7, 8, 9]]])

In [11]:
TENSOR.ndim

3

In [12]:
TENSOR.shape

torch.Size([1, 3, 3])

In [13]:
TeNsOr = torch.tensor(
    [
        [
            [
                [1, 2, 3, 4],
                [4, 5, 6, 4],
                [7, 8, 9, 4],
            ],
            [
                [1, 2, 3, 4],
                [4, 5, 6, 4],
                [7, 8, 9, 4],
            ],
        ],
        [
            [
                [1, 2, 3, 4],
                [4, 5, 6, 4],
                [7, 8, 9, 4],
            ],
            [
                [1, 2, 3, 4],
                [4, 5, 6, 4],
                [7, 8, 9, 4],
            ],
        ],
    ]
)
TeNsOr.shape

torch.Size([2, 2, 3, 4])

In [14]:
TeNsOr.ndim

4

## Random Tensor
#### Why Random Tensors
# Random tensors are important because the way many neural network is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.
# ` Start with random numbers -> look at data -> update random number -> look at data -> update random numbers`

In [15]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(1,3,4)
random_tensor

tensor([[[0.7907, 0.3560, 0.7583, 0.7415],
         [0.0814, 0.6457, 0.0648, 0.6138],
         [0.1875, 0.3526, 0.0503, 0.2992]]])

In [16]:
random_tensor.ndim

3

In [17]:
random_tensor.shape

torch.Size([1, 3, 4])

In [18]:
# Create a random tensor with simialr shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))

### Zeros and ones

In [24]:
# Create a tensor of all zeros 
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
zero*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [27]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32