In [4]:
import torch
import pandas as pd
import numpy as np

print(torch.__version__)

2.9.1+cpu


### Creating a range of tensors and tensors-like

In [5]:
# Use torch.range()
torch.range(1,10,2)

C:\Users\Haji Suleman\AppData\Local\Temp\ipykernel_10960\1134511046.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10,2)


tensor([1., 3., 5., 7., 9.])

In [ ]:
#Use torch.range and get deprecated message, use torch.arange()
one_to_ten =  torch.arange(start=1,end=11,step=1)
one_to_ten


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])