In [18]:
import pandas as pd
import torch
import numpy as np


## Reshaping, stacking, squeezing  and unsqueezing tensors

* Reshaping - reshapes an input tensor  to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking -  combine multiple tensors on the top of each other (vstack) or side by side (hstack)

* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [19]:
# Let's create a tensor
x  = torch.arange(1.,13.)
x,x.shape 

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [20]:
x_Reshaped = x.reshape(6,2)
x_Reshaped, x_Reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [21]:
x_Viewed = x.view(6,2)
x_Viewed,x_Viewed.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]),
 torch.Size([6, 2]))

In [22]:
# Changing x_Viewed changes x_Reshaped (because a view of a tensor shares the same memory as the original input)

x_Viewed[:,0] = 5
x,x_Viewed

(tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.,  5., 12.]),
 tensor([[ 5.,  2.],
         [ 5.,  4.],
         [ 5.,  6.],
         [ 5.,  8.],
         [ 5., 10.],
         [ 5., 12.]]))

In [24]:
x_stacked = torch.stack([x,x,x])
x_stacked

tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.,  5., 12.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.,  5., 12.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.,  5., 12.]])

In [42]:
# torch.squeeze()-remove all single dimentions from target tensor
x = torch.tensor([[3, 4, 5]])
print(x.squeeze(dim=1))

tensor([[3, 4, 5]])


In [ ]:
# torch.unsqueeze - adds a single dimention to a target tensor at a specific dim (dimension) 

In [147]:
# permute
x = torch.rand(size=(224, 224, 3))
print(torch.permute(x, (2, 0, 1)).size())

torch.Size([3, 224, 224])
